### ISSUE TITLE
How to produce conventional skipgrams?

### ISSUE THREAD

**Issue by glicerico** [jkamalu/skipgram_sklearn#1]
Thanks for implementing this :)

Could you please explain what kind of skipgrams your code produces? It doesn't seem to produce them in the conventional way: https://github.com/nltk/nltk/blob/develop/nltk/util.py#L538

**Comment by jkamalu** [comment]
If you're still looking for an answer, if I remember correctly you can specify a window size and a skipping range (L, R) with L>=0, L<=R, and R<window size (my best guess, not having looked at this in a while).

For example, you could say window=4, skip_range=(1,2) and then in the sentence "I love a good joke" your skip grams would be (I, good) and (love, joke). Any other choice for a range with len=2 for this example would have been trivial by the way. If you chose skip_range=(1,1), then your skip grams would be (I, a, good) and (love, good, joke).

You'll have to check the code for the exact API but hope this helps.
